# Generated by Django 5.2.14 on 2026-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_unique_together_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
    ]
