# Generated by Django 5.2.14 on 2026-06-05 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('key_insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('period_analyzed', models.CharField(max_length=100)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'análise IA',
                'verbose_name_plural': 'análises IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_aianalys_user_id_9d3faa_idx'), models.Index(fields=['user', 'is_latest'], name='ai_aianalys_user_id_6142b9_idx')],
            },
        ),
    ]
